site_name: Future Energy Outlook (FEO)
site_url: ""
plugins:
  - search
  - multirepo:
      cleanup: false
      nav_repos:
        - name: feo-esmod-osemosys
          import_url: https://github.com/transition-zero/feo-esmod-osemosys
          imports: [docs/index.md,
                    docs/1_indonesia.md,
                    docs/figures/*]
  - table-reader

nav:
  - Home: index.md
  - Systems modelling: 
    - 'FEO Global': feo-esmod-osemosys/docs/index.md
    - 'Indonesia': feo-esmod-osemosys/docs/1_indonesia.md
  - Data Catalog: feo-data-catalog.md
  - Python Client: feo-python-client.md
  - API: feo-api.md

theme:
  name: material
  font:
    text: Roboto
    code: Roboto Mono
  palette:
    primary: amber
    accent: indigo
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.instant
    - navigation.tracking
    - navigation.sections
  logo: _static/tz_logo.svg
  favicon: _static/tz_logo_small.svg
  


  
  

    
